INSERT INTO category (categoryName, categoryId) values ('Film & Animation', 1);
INSERT INTO category (categoryName, categoryId) values ('Autos & Vehicles', 2);
INSERT INTO category (categoryName, categoryId) values ('Music', 10);
INSERT INTO category (categoryName, categoryId) values ('Pets & Animals', 15);
INSERT INTO category (categoryName, categoryId) values ('Sports', 17);
INSERT INTO category (categoryName, categoryId) values ('Short Movies', 18);
INSERT INTO category (categoryName, categoryId) values ('Travel & Events', 19);
INSERT INTO category (categoryName, categoryId) values ('Gaming', 20);
INSERT INTO category (categoryName, categoryId) values ('Videoblogging', 21);
INSERT INTO category (categoryName, categoryId) values ('People & Blogs', 22);
INSERT INTO category (categoryName, categoryId) values ('Comedy', 23);
INSERT INTO category (categoryName, categoryId) values ('Entertainment', 24);
INSERT INTO category (categoryName, categoryId) values ('News & Politics', 25);
INSERT INTO category (categoryName, categoryId) values ('Howto & Style', 26);
INSERT INTO category (categoryName, categoryId) values ('Education', 27);
INSERT INTO category (categoryName, categoryId) values ('Science & Technology', 28);
INSERT INTO category (categoryName, categoryId) values ('Nonprofits & Activism', 29);
INSERT INTO category (categoryName, categoryId) values ('Movies', 30);
INSERT INTO category (categoryName, categoryId) values ('Anime/Animation', 31);
INSERT INTO category (categoryName, categoryId) values ('Action/Adventure', 32);
INSERT INTO category (categoryName, categoryId) values ('Classics', 33);
INSERT INTO category (categoryName, categoryId) values ('Documentary', 35);
INSERT INTO category (categoryName, categoryId) values ('Drama', 36);
INSERT INTO category (categoryName, categoryId) values ('Family', 37);
INSERT INTO category (categoryName, categoryId) values ('Foreign', 38);
INSERT INTO category (categoryName, categoryId) values ('Horror', 39);
INSERT INTO category (categoryName, categoryId) values ('Sci-Fi/Fantasy', 40);
INSERT INTO category (categoryName, categoryId) values ('Thriller', 41);
INSERT INTO category (categoryName, categoryId) values ('Shorts', 42);
INSERT INTO category (categoryName, categoryId) values ('Shows', 43);
INSERT INTO category (categoryName, categoryId) values ('Trailers', 44);
